Repository UBC-MDS/DSCI-532_2024_17_Global-CO2-Emissions-Tracker, pull requests merged in 2024-04, with the labels that each got.

#33 created requirements file for rendering
  requirements.txt
Labels: render setup

#38 Add the skeleton and finish code in app.py file for milestone2
  data/proceed/carbon_emission_proceed.csv
  data/raw/region.csv
  img/top_emitters_bar.png
  notebooks/eda.ipynb
  src/app.py
Labels: code

#39 create demo.gif for the dashboard usage
  img/demo.gif
Labels: image

#40 Created reflection for milestone 2
  reports/m2_reflection.md
Labels: documentation

#42 Adjusted README.md to update with Milestone2 requests
  README.md
Labels: documentation

#51 Modified app.py file: adjust the y-axis range for bar chart and removed the x-axis label
  reports/m3_reflection.md
  src/app.py
  src/callbacks.py
  src/components.py
  src/data.py
Labels: code

#56 Deployment troubleshooting
  src/__init__.py
  src/app.py
Labels: bug

#71 addressed comments about bar plots, pie plots and color
  data/proceed/carbon_emission_proceed.parquet
  environment.yaml
  notebooks/eda.ipynb
  requirements.txt
  src/app.py
  src/cache-directory/2029240f6d1128be89ddc32729463129
  src/cache-directory/499e884740417c055528ae69565b093a
  src/cache-directory/6770ea77368df8c094f4cfe273cf810f
  src/cache-directory/846c4b2f6316da792a6851b3d161a515
  src/cache-directory/a5278151ee8210369062e081a1c1c7eb
  src/cache-directory/d8fa2b4a89b81b6efc6896933f8ac9c5
  src/cache-directory/ec20dea377a90b3c343cb9ab0f6dd68d
  src/cache-directory/f455b6a09c91167add4dc462f7fdd335
  src/callbacks.py
  src/components.py
  src/data.py
Labels: code

#80 Create milestone 4 reflection
  reports/m4_reflection.md
Labels: documentation

#81 added the footer to dashboard
  src/components.py
Labels: code
